# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4329681ada3ea67e7542ab42763f58e0d277a316f28fccde94a3ca0bfc29c137d304bc6fa70eeb649874d78f38f90d15a7992422521c257bdec41f276a35df3f

test:
  secret_key_base: e34a57dd3890cd3a96305097a7d8825d68422185d8f7fc79fb5e459d99f8aae28a2f5583290c36cd78a6f6cc39c723ab077fde76412b034bebcc5554323c29d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
